### ISSUE TITLE
Client profile v2 epic and launch ticket

### ISSUE THREAD

**Issue by sychang** [Recidiviz/case-triage#84]
**What needs to be done? Why does it need to be done?**
Overall epic to summarize work bundled. Combining this with a launch checklist. All items should be checked off prior to flipping the feature flag. 

PRD: https://docs.google.com/document/d/1m1_NrC42_k0yLaHPi-N4T0nZI4hKbxIbpbleRVlYwR8/edit#

Mocks: https://www.figma.com/file/UZi1Mp4W0nINg6hB5OHFXI/Line-Staff?node-id=5095%3A949

- [ ] Put all client profile updates behind a feature flag
- [ ] Custom client details and details panel (#85)
- [ ] New panel (link ticket when finalized)

Review before feature flag can be flipped
- [ ] QA
- [ ] Product
- [ ] Data
- [ ] Eng
- [ ] Design

**Additional context**
Add any other context about the task here.

**Comment by sychang** [comment]
Closing because created this in the wrong repo, recreating here: https://app.zenhub.com/workspaces/cosmos-aka-line-staff-tools-5fd7950b2ceba10011b87ebd/issues/recidiviz/recidiviz-data/7549
