### ISSUE TITLE
Client profile v2: Details panel and custom details

### ISSUE THREAD

**Issue by sychang** [Recidiviz/case-triage#85]
**What needs to be done? Why does it need to be done?**
PRD: https://docs.google.com/document/d/1m1_NrC42_k0yLaHPi-N4T0nZI4hKbxIbpbleRVlYwR8/edit#

Mocks: https://www.figma.com/file/UZi1Mp4W0nINg6hB5OHFXI/Line-Staff?node-id=5095%3A949

This includes the following changes
- [ ] Adding preferred name
- [ ] Adding best mode of contact
- [ ] Creating a summary section with supervision start date and time on supervision
- [ ] Address
- [ ] Client email address
- [ ] Client phone number
- [ ] Client employer
- [ ] Creating an "Upcoming" section and link IDOC policies
- [ ] Show date and type of upcoming contact, as well as date and type of previous contact
- [ ] Show date of upcoming risk assessment, as well as date of previous risk assessment
- [ ] Creating an "Events" section that shows the following [NOT FINALIZED: Whether we include a button to show "full history" or show it by default. Decide pending data complexity investigations)
- [ ] If their birthday is this month and ability to email a happy birthday  
- [ ] Previous risk assessments, and an indicator iff their score has decreased
- [ ] Previous contact dates, types, and notes from CIS
- [ ] Milestones on supervision, as detailed [here](https://docs.google.com/document/d/1m1_NrC42_k0yLaHPi-N4T0nZI4hKbxIbpbleRVlYwR8/edit#bookmark=id.bhonbnr44el9)
- [ ] Implement finalized copy [NOT FINALIZED as of 5/20: Serena] 

The following changes are out of scope
- Addition of the 'New' tab in the client profile
- Data quality reporting flow for the details page - we will encourage POs to submit feedback via intercom. Item-level reporting flow will be present in the 'New' tab later  

**Additional context**
Add any other context about the task here.

**Comment by sychang** [comment]
Closing because made this in wrong repo. Correct issue: https://app.zenhub.com/workspaces/cosmos-aka-line-staff-tools-5fd7950b2ceba10011b87ebd/issues/recidiviz/recidiviz-data/7550
